### ISSUE TITLE
Relative links not working

### ISSUE THREAD

**Issue by msolberg** [tosin2013/openshiftv4-devday-homeroom#1]
Looks like relative links might be broken within the content. For example:

on https://<cluster>/user/user2/workshop/exercises/2-DeployAppUsingWebConsole, if I click on the link in "Log into Developer Console as explained here and create a project, if you have not already done so", I get a 404 trying to go to:

https://<cluster>/user/user2/workshop/exercises/1.ExploreDeveloperConsole.html

There's another link like that at the bottom of the ExploreDeveloperConsole page.

**Comment by tosin2013** [comment]
This should be fixed with the new container image. 

https://github.com/tosin2013/openshiftv4-devday-homeroom/commit/1042d31460eed3f2691ed6ffd58eea4facdec740

quay.io/takinosh/openshiftv4-devday:v0.0.3
