### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by msolberg** [tosin2013/openshiftv4-devday-homeroom#2]
image::devconsoleapp1.png[image]

on "Deploy an Application Using Web Console". There are also missing images towards the bottom of the page which should have the icons on the application circle.

**Comment by tosin2013** [comment]
This has been corrected 

https://github.com/tosin2013/openshiftv4-devday-homeroom/commit/dba9b7a5c582be40ab198946b1c36e619863f3b2
